"""Context Packs (Builder Edition, Chapter 14).

Context Packs are governed repository memory prepared for humans and AI agents.
They contain supported claims, decisions, uncertainty, tests to run, and explicit
"do not change without review" warnings.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone

from devtime.intelligence.claims import ConceptIntelligence

MODES = ("overview", "risk", "implementation", "testing", "onboarding", "security")


@dataclass
class ContextPack:
    concept: str
    mode: str
    purpose: str
    supported_claims: list[str] = field(default_factory=list)
    decisions: list[str] = field(default_factory=list)
    uncertainty: list[str] = field(default_factory=list)
    do_not_change: list[str] = field(default_factory=list)
    tests_to_run: list[str] = field(default_factory=list)
    agent_guidance: str = ""
    generated_at: str = ""


def _do_not_change_warnings(ci: ConceptIntelligence) -> list[str]:
    """Derive 'do not change' warnings from actual evidence, never a hardcoded
    per-name table.

    Reality Validation finding: the old table asserted billing-specific warnings
    ("Subscription state transition mapping") for a generic webhook system with no
    billing evidence — a claim with no evidence. Warnings must follow evidence.
    """
    kinds = {e.signal.kind for e in ci.evidence}
    warnings: list[str] = []
    if "webhook_signature_verification" in kinds:
        warnings.append("Webhook signature verification behavior.")
    if "token_usage" in kinds:
        warnings.append("Token issuing and verification behavior.")
    if "auth_dependency" in kinds or "middleware" in kinds:
        warnings.append("Authorization / protected-route behavior.")
    if "route" in kinds:
        warnings.append(f"Request handling behavior for {ci.concept.name}.")
    if "background_job" in kinds or "queue" in kinds:
        warnings.append("Job/queue processing behavior.")
    if not warnings:
        warnings.append(f"Core behavior of {ci.concept.name} without a reviewer.")
    return warnings


def generate_context_pack(ci: ConceptIntelligence, mode: str = "risk") -> ContextPack:
    if mode not in MODES:
        mode = "risk"

    supported = [
        f"{c.text} Evidence: "
        f"{', '.join(dict.fromkeys(e.path for e in c.evidence if e.path)) or 'n/a'}"
        for c in ci.claims
        if c.type != "uncertainty" and c.state in ("supported", "weak")
    ]
    decisions = [
        e.summary for e in ci.evidence if e.kind == "decision"
    ] or ["No decision record found."]
    uncertainty = [u.text for u in ci.uncertainties]
    tests = list(
        dict.fromkeys(e.path for e in ci.evidence if e.signal.kind == "test" and e.path)
    )

    if ci.uncertainties:
        guidance = (
            "Do not invent rationale for missing decisions. "
            "Ask a human or record a decision before changing core behavior."
        )
    else:
        guidance = "Preserve existing behavior and keep evidence links intact."

    return ContextPack(
        concept=ci.concept.name,
        mode=mode,
        purpose=f"{ci.concept.name} is detected from repository evidence.",
        supported_claims=supported,
        decisions=decisions,
        uncertainty=uncertainty,
        do_not_change=_do_not_change_warnings(ci),
        tests_to_run=tests or ["No behavior-specific tests found."],
        agent_guidance=guidance,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )


def render_markdown(pack: ContextPack) -> str:
    lines = [
        f"# Context Pack: {pack.concept}",
        f"Mode: {pack.mode}",
        "Generated by: DevTime",
        "Source: local repository memory",
        "",
        "## Purpose",
        pack.purpose,
        "",
        "## Supported Claims",
    ]
    lines += [f"- {c}" for c in pack.supported_claims] or ["- None"]
    lines += ["", "## Decisions"]
    lines += [f"- {d}" for d in pack.decisions]
    lines += ["", "## Uncertainty"]
    lines += [f"- {u}" for u in pack.uncertainty] or ["- None"]
    lines += ["", "## Do Not Change Without Review"]
    lines += [f"- {w}" for w in pack.do_not_change]
    lines += ["", "## Tests To Run"]
    lines += [f"- {t}" for t in pack.tests_to_run]
    lines += ["", "## Agent Instruction", pack.agent_guidance]
    return "\n".join(lines)
